#!/bin/bash
# Configure FreeIPA installation based on discovered network properties
# Supports AUTO, STATIC, and HYBRID configuration modes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "========================================="
echo "FreeIPA Dynamic Configuration"
echo "========================================="
echo ""

# Load environment configuration
ENV_FILE="${PROJECT_ROOT}/.env"
if [ -f "$ENV_FILE" ]; then
    echo "Loading configuration from .env"
    # shellcheck source=/dev/null
    source "$ENV_FILE"
    echo ""
fi

# Get configuration mode
CONFIG_MODE="${NETWORK_CONFIG_MODE:-AUTO}"

echo "Configuration Mode: $CONFIG_MODE"
echo ""

# Run discovery script
echo "Discovering network configuration..."
DISCOVERED_ENV=$("$SCRIPT_DIR/discover-network-config.sh" env | grep '^DISCOVERED_\|^RECOMMENDED_')

# Parse discovered configuration
eval "$DISCOVERED_ENV"

echo "Network discovery complete"
echo ""

# Determine final configuration based on mode
echo "Determining final configuration..."
echo ""

case "$CONFIG_MODE" in
    AUTO)
        echo "Mode: AUTO - Using discovered network properties"

        FREEIPA_DOMAIN="${RECOMMENDED_FREEIPA_DOMAIN}"
        FREEIPA_REALM="${RECOMMENDED_REALM}"
        FREEIPA_SERVER_HOSTNAME="ipa.${RECOMMENDED_FREEIPA_DOMAIN}"
        FREEIPA_SERVER_IP="${DISCOVERED_IPV4_ADDR}"

        # No public domain in AUTO mode
        PUBLIC_DOMAIN=""
        CLOUDFLARE_TUNNEL_ENABLED=false

        echo "  FreeIPA Domain: $FREEIPA_DOMAIN"
        echo "  Kerberos Realm: $FREEIPA_REALM"
        echo "  Server Hostname: $FREEIPA_SERVER_HOSTNAME"
        echo "  Server IP: $FREEIPA_SERVER_IP"
        ;;

    STATIC)
        echo "Mode: STATIC - Using .env configuration"

        # Validate required variables
        if [ -z "${FREEIPA_DOMAIN:-}" ]; then
            echo "Error: FREEIPA_DOMAIN not set in .env"
            exit 1
        fi
        if [ -z "${FREEIPA_REALM:-}" ]; then
            echo "Error: FREEIPA_REALM not set in .env"
            exit 1
        fi

        # Use values from .env (already loaded)
        FREEIPA_SERVER_HOSTNAME="${FREEIPA_SERVER_HOSTNAME:-ipa.$FREEIPA_DOMAIN}"
        FREEIPA_SERVER_IP="${FREEIPA_SERVER_IP:-$DISCOVERED_IPV4_ADDR}"
        PUBLIC_DOMAIN="${PUBLIC_DOMAIN:-}"
        CLOUDFLARE_TUNNEL_ENABLED="${CLOUDFLARE_TUNNEL_ENABLED:-false}"

        echo "  FreeIPA Domain: $FREEIPA_DOMAIN"
        echo "  Kerberos Realm: $FREEIPA_REALM"
        echo "  Server Hostname: $FREEIPA_SERVER_HOSTNAME"
        echo "  Server IP: $FREEIPA_SERVER_IP"
        if [ -n "$PUBLIC_DOMAIN" ]; then
            echo "  Public Domain: $PUBLIC_DOMAIN"
        fi
        ;;

    HYBRID)
        echo "Mode: HYBRID - Local + public domain via Cloudflare Tunnel"

        # Check if Cloudflare WARP is enabled
        if [ "$DISCOVERED_WARP_ENABLED" != "true" ]; then
            echo "Warning: HYBRID mode recommended with Cloudflare WARP"
            echo "WARP not detected, but continuing..."
            echo ""
        fi

        # Use .env configuration (already loaded)
        if [ -z "${FREEIPA_DOMAIN:-}" ]; then
            echo "Error: FREEIPA_DOMAIN not set in .env for HYBRID mode"
            exit 1
        fi
        if [ -z "${FREEIPA_REALM:-}" ]; then
            echo "Error: FREEIPA_REALM not set in .env for HYBRID mode"
            exit 1
        fi
        if [ -z "${PUBLIC_DOMAIN:-}" ]; then
            echo "Error: PUBLIC_DOMAIN not set in .env for HYBRID mode"
            exit 1
        fi

        FREEIPA_SERVER_HOSTNAME="${FREEIPA_SERVER_HOSTNAME:-ipa.$FREEIPA_DOMAIN}"
        FREEIPA_SERVER_IP="${FREEIPA_SERVER_IP:-$DISCOVERED_IPV4_ADDR}"
        CLOUDFLARE_TUNNEL_ENABLED=true

        echo "  Local FreeIPA Domain: $FREEIPA_DOMAIN"
        echo "  Public Domain: $PUBLIC_DOMAIN"
        echo "  Kerberos Realm: $FREEIPA_REALM"
        echo "  Server Hostname: $FREEIPA_SERVER_HOSTNAME"
        echo "  Server IP: $FREEIPA_SERVER_IP"
        echo "  Cloudflare Tunnel: Enabled"
        ;;

    *)
        echo "Error: Unknown configuration mode '$CONFIG_MODE'"
        echo "Valid modes: AUTO, STATIC, HYBRID"
        exit 1
        ;;
esac

echo ""

# Generate Ansible variables file
ANSIBLE_VARS_FILE="${PROJECT_ROOT}/playbooks/group_vars/discovered.yml"

echo "Generating Ansible configuration..."

mkdir -p "${PROJECT_ROOT}/playbooks/group_vars"

cat > "$ANSIBLE_VARS_FILE" <<EOF
---
# Automatically generated by configure-freeipa-dynamic.sh
# Generated: $(date)
# Configuration Mode: $CONFIG_MODE

# Network Discovery
discovered_network:
  hostname:
    short: "$DISCOVERED_HOSTNAME_SHORT"
    fqdn: "$DISCOVERED_HOSTNAME_FQDN"
    domain: "$DISCOVERED_HOSTNAME_DOMAIN"

  network:
    default_interface: "$DISCOVERED_DEFAULT_IFACE"
    ipv4:
      address: "$DISCOVERED_IPV4_ADDR"
      cidr: "$DISCOVERED_IPV4_CIDR"
      network: "$DISCOVERED_IPV4_NETWORK"
    ipv6:
      gua: "$DISCOVERED_IPV6_GUA"
      lla: "$DISCOVERED_IPV6_LLA"

# FreeIPA Configuration
freeipa_domain: "$FREEIPA_DOMAIN"
freeipa_realm: "$FREEIPA_REALM"
freeipa_hostname: "$FREEIPA_SERVER_HOSTNAME"
freeipa_ip_address: "$FREEIPA_SERVER_IP"
freeipa_setup_dns: true
freeipa_configure_dns_forwarders: true

# Configuration Mode
network_config_mode: "$CONFIG_MODE"

EOF

# Add HYBRID mode specific configuration
if [ "$CONFIG_MODE" = "HYBRID" ]; then
    cat >> "$ANSIBLE_VARS_FILE" <<EOF
# HYBRID Mode - Public Domain Configuration
public_domain: "$PUBLIC_DOMAIN"
cloudflare_tunnel_enabled: true

EOF
fi

# Add Kudu server DNS records
cat >> "$ANSIBLE_VARS_FILE" <<EOF
# Kudu Server DNS Records
kudu_servers:
  - name: kudu-master
    fqdn: "kudu-master.$FREEIPA_DOMAIN"
    ip: "$FREEIPA_SERVER_IP"
    role: master
    service_principal: "kudu/kudu-master.$FREEIPA_DOMAIN@$FREEIPA_REALM"

  - name: kudu-tserver-1
    fqdn: "kudu-tserver-1.$FREEIPA_DOMAIN"
    ip: "$FREEIPA_SERVER_IP"
    role: tserver
    service_principal: "kudu/kudu-tserver-1.$FREEIPA_DOMAIN@$FREEIPA_REALM"

# Knative Configuration
knative_wildcard_ip: "$FREEIPA_SERVER_IP"
knative_domain: "knative.$FREEIPA_DOMAIN"

# DNS Forwarders (upstream DNS)
dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4
EOF

echo "Ansible variables written to: $ANSIBLE_VARS_FILE"
echo ""

# Generate .env updates
ENV_UPDATES_FILE="${PROJECT_ROOT}/.env.freeipa-discovered"

echo "Generating .env configuration..."

cat > "$ENV_UPDATES_FILE" <<EOF
# FreeIPA Configuration (discovered $(date))
# Generated by configure-freeipa-dynamic.sh
# Append to .env or review and merge manually

# Configuration Mode
NETWORK_CONFIG_MODE="$CONFIG_MODE"

# FreeIPA Settings
FREEIPA_DOMAIN="$FREEIPA_DOMAIN"
FREEIPA_REALM="$FREEIPA_REALM"
FREEIPA_SERVER_HOSTNAME="$FREEIPA_SERVER_HOSTNAME"
FREEIPA_SERVER_IP="$FREEIPA_SERVER_IP"

# Network Information
KUDU_MASTER_IP="$FREEIPA_SERVER_IP"
KUDU_TSERVER_IP="$FREEIPA_SERVER_IP"

EOF

if [ "$CONFIG_MODE" = "HYBRID" ]; then
    cat >> "$ENV_UPDATES_FILE" <<EOF
# HYBRID Mode - Public Domain
PUBLIC_DOMAIN="$PUBLIC_DOMAIN"
CLOUDFLARE_TUNNEL_ENABLED="true"

# Public endpoints (via Cloudflare Tunnel)
KUDU_MASTER_PUBLIC_URL="https://kudu-master.$PUBLIC_DOMAIN"
KUDU_TSERVER_PUBLIC_URL="https://kudu-tserver.$PUBLIC_DOMAIN"
FREEIPA_PUBLIC_URL="https://ipa.$PUBLIC_DOMAIN"

EOF
fi

echo ".env configuration written to: $ENV_UPDATES_FILE"
echo ""

# Summary
echo "========================================="
echo "Configuration Summary"
echo "========================================="
echo ""

echo "Configuration Mode: $CONFIG_MODE"
echo ""

echo "FreeIPA Configuration:"
echo "  Domain: $FREEIPA_DOMAIN"
echo "  Realm: $FREEIPA_REALM"
echo "  Server: $FREEIPA_SERVER_HOSTNAME ($FREEIPA_SERVER_IP)"
echo ""

if [ "$CONFIG_MODE" = "HYBRID" ]; then
    echo "Public Domain: $PUBLIC_DOMAIN"
    echo "  Master UI: https://kudu-master.$PUBLIC_DOMAIN"
    echo "  Tablet Server UI: https://kudu-tserver.$PUBLIC_DOMAIN"
    echo "  FreeIPA UI: https://ipa.$PUBLIC_DOMAIN"
    echo ""
fi

echo "Next Steps:"
echo ""

if [ ! -f "$ENV_FILE" ]; then
    echo "  1. Review and copy .env configuration:"
    echo "     cp $ENV_UPDATES_FILE .env"
else
    echo "  1. Configuration already in .env (HYBRID mode)"
fi

echo ""
echo "  2. Run Ansible playbook to install FreeIPA:"
echo "     cd playbooks"
echo "     ./quickstart.sh"
echo "     # Or manually:"
echo "     ansible-playbook -i inventory/hosts freeipa-install.yml"
echo ""

if [ "$CONFIG_MODE" = "HYBRID" ]; then
    echo "  3. Configure Cloudflare Tunnel:"
    echo "     cd infrastructure/scripts"
    echo "     ./setup-cloudflare-tunnel.sh"
    echo ""
fi

echo "  4. Test FreeIPA installation:"
echo "     kinit admin@$FREEIPA_REALM"
echo "     ipa user-show admin"
echo ""

echo "========================================="
echo "Configuration Complete"
echo "========================================="
